source 'https://rubygems.org'
ruby '1.9.3'
#ruby-gemset=mybook_rails_4_0
gem 'rails'

group :development do
	gem 'sqlite3'
end

group :assets do
  gem 'sass-rails'
  gem 'coffee-rails'
  gem 'uglifier'
end

gem 'jquery-rails'
gem 'turbolinks'

gem 'jbuilder'

group :doc do
	gem 'sdoc', require: false
end
