source 'https://rubygems.org'
ruby '1.9.3'
#ruby-gemset=mybook_rails_4_0
gem 'rails', '3.2.13'

group :development do
	gem 'sqlite3', '1.3.7'
end

group :assets do
  gem 'sass-rails',   '~> 4.0.0'
  gem 'coffee-rails', '~> 4.0.0'
  gem 'uglifier', '>= 1.3.0'
end

gem 'jquery-rails' ,'2.2.1'

gem 'turbolinks'

gem 'jbuilder'

group :doc do
	gem 'sdoc', require: false
end
